## Conversion of Wyrmspan Game Cards to JSON format

In [21]:
import pandas as pd
import json

Convert xlsx file to json format

In [22]:
cards_df = pd.read_csv('cards.csv')
cards_df

,type,number,name,ability,abilityType,VP,size,capacity,personality,Meat,Gold,Crystal,Coin,Crimson Cavern,Golden Grotto,Amethyst Abyss,Egg,Milk
0,Dragon,1,White-Bellied Grazer,Cache [Milk] from your supply here. Any time y...,Adventurer,4.0,Hatchling,NaN,Shy,NaN,NaN,NaN,NaN,NaN,x,NaN,1.0,1.0
1,Dragon,2,Genial Mothdragon,Tuck [DragonCard] from your hand here. Any tim...,Adventurer,5.0,Hatchling,NaN,Helpful,NaN,NaN,NaN,NaN,x,NaN,NaN,1.0,3.0
2,Dragon,3,Algal Lindworm,Cache [Milk] from your supply here. Any time y...,Adventurer,3.0,Hatchling,NaN,Helpful,NaN,NaN,NaN,NaN,NaN,x,x,1.0,3.0
3,Dragon,4,Frugivorous Grazer,Cache [Milk] from your supply here. Any time y...,Adventurer,2.0,Hatchling,NaN,Shy,NaN,NaN,NaN,NaN,NaN,NaN,x,1.0,2.0
4,Dragon,5,Fanged Feydragon,Cache [Meat] from your supply here. Any time y...,Adventurer,0.0,Hatchling,NaN,Playful,NaN,NaN,NaN,NaN,NaN,x,NaN,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,Cave,71,NaN,"Up to 3x, pay [CaveCard] to gain [DragonGuild]...",WhenPlayed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,Cave,72,NaN,"Up to 3x, pay [DragonCard] to gain [DragonGuil...",WhenPlayed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,Cave,73,NaN,"Up to 3x, pay [DragonCard] to lay [Egg][Egg]. ...",WhenPlayed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,Cave,74,NaN,"Up to 3x, pay [Egg] to gain [AnyResource][AnyR...",WhenPlayed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,Cave,75,NaN,"Up to 3x, pay [Egg] to gain [DragonGuild]. Eac...",WhenPlayed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# save the dragon cards first in json format
dragon_cards = cards_df[cards_df['type'] == 'Dragon']
dragon_cards = dragon_cards.drop(columns=['type'])

# replace NaNs and change types to int for some columns
for col in ['VP','capacity','Meat','Gold','Crystal','Coin','Egg','Milk']:
    dragon_cards[col] = dragon_cards[col].fillna(0)
    dragon_cards[col] = dragon_cards[col].astype(int)

for col in ['Crimson Cavern','Golden Grotto','Amethyst Abyss']:
    dragon_cards[col] = dragon_cards[col].fillna(False)
    dragon_cards[col] = dragon_cards[col].astype(bool)

dragon_cards = dragon_cards.rename(columns={'ability':'ability_text','Meat':'meat_cost','Gold':'gold_cost','Crystal':'crystal_cost','Coin':'coin_cost','Egg':'egg_cost','Milk':'milk_cost'})

dragon_cards.info()
dragon_cards

<class 'pandas.core.frame.DataFrame'>
Index: 183 entries, 0 to 182
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   number          183 non-null    int64
 1   name            183 non-null    object
 2   ability_text    183 non-null    object
 3   abilityType     183 non-null    object
 4   VP              183 non-null    int32
 5   size            183 non-null    object
 6   capacity        183 non-null    int32
 7   personality     183 non-null    object
 8   meat_cost       183 non-null    int32
 9   gold_cost       183 non-null    int32
 10  crystal_cost    183 non-null    int32
 11  coin_cost       183 non-null    int32
 12  Crimson Cavern  183 non-null    bool
 13  Golden Grotto   183 non-null    bool
 14  Amethyst Abyss  183 non-null    bool
 15  egg_cost        183 non-null    int32
 16  milk_cost       183 non-null    int32
dtypes: bool(3), int32(8), int64(1), object(5)
memory usage: 16.3+ KB

,number,name,ability_text,abilityType,VP,size,capacity,personality,meat_cost,gold_cost,crystal_cost,coin_cost,Crimson Cavern,Golden Grotto,Amethyst Abyss,egg_cost,milk_cost
0,1,White-Bellied Grazer,Cache [Milk] from your supply here. Any time y...,Adventurer,4,Hatchling,0,Shy,0,0,0,0,False,True,False,1,1
1,2,Genial Mothdragon,Tuck [DragonCard] from your hand here. Any tim...,Adventurer,5,Hatchling,0,Helpful,0,0,0,0,True,False,False,1,3
2,3,Algal Lindworm,Cache [Milk] from your supply here. Any time y...,Adventurer,3,Hatchling,0,Helpful,0,0,0,0,False,True,True,1,3
3,4,Frugivorous Grazer,Cache [Milk] from your supply here. Any time y...,Adventurer,2,Hatchling,0,Shy,0,0,0,0,False,False,True,1,2
4,5,Fanged Feydragon,Cache [Meat] from your supply here. Any time y...,Adventurer,0,Hatchling,0,Playful,0,0,0,0,False,True,False,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,179,Nurturing Feydragon,Gain an additional [VP-1] for every 2 [Egg] yo...,EndGame,2,Small,4,Helpful,1,1,1,0,True,True,True,0,0
179,180,Beckoning Cricketcatcher,Gain [DragonCard]. You may tuck it under any d...,OncePerRound,4,Small,2,Aggressive,1,1,0,0,False,True,False,0,0
180,181,Gamboling Landragon,Gain [Meat][Meat]. Each opponent gains [Meat].,WhenPlayed,3,Large,1,Playful,1,0,0,0,True,False,False,0,0
181,182,Waddy's Rufftail,Gain [Meat].,Adventurer,4,Medium,3,Aggressive,1,2,0,0,False,True,False,0,0
182,183,Warming Firevern,Gain [VP-1] for each HELPFUL dragon on your pl...,EndGame,5,Large,2,Helpful,2,2,0,0,True,True,False,0,0

In [46]:
dragon_dict = dragon_cards.to_dict(orient='records')

for card in dragon_dict:
    ability_string = card['ability_text']
    ability_info = {'adv_effects': {}}
    # split text by commas and periods
    as1 = ability_string.split(',')
    ability_strings = []
    for a in as1:
        ability_strings.extend(a.split('.'))
    # process each string
    for a in ability_strings:
        a = a.lower()
        if 'up to' in a and 'x' in a:
            ability_info['max_uses'] = int(a[-2])
        if 'pay' in a:
            ability_info['cost'] = {}
            ability_info['cost'][a] = 1
        if 'may' in a:
            ability_info['adv_effects']['choice'] = []
        if ('gain' in a or 'lay [egg]' in a or 'tuck' in a) and 'vp' not in a:
            gain_list = ability_info['adv_effects'].get('sequence', [])
            gain_list.append({'gain_': {'type': a, 'amount': 1}})
            ability_info['adv_effects']['sequence'] = gain_list
        if 'opponent' in a:
            ability_info['opponent_effect'] = {'adv_effects': {}}
        if 'if' in a:
            ability_info['condition'] = {'and': [a]}
    # update the card
    if card['abilityType'] == 'Adventurer':
        card['if_activated'] = ability_info
    elif card['abilityType'] == 'OncePerRound':
        card['once_per_round'] = ability_info
    elif card['abilityType'] == 'EndGame':
        card['end_game'] = ability_info
    elif card['abilityType'] == 'WhenPlayed':
        card['when_played'] = ability_info
    card.pop('abilityType')

    if card['size'] == 'Hatchling':
        card['on_feed'] = {'gain_': {'type': '', 'amount': 1}}
        card['on_grow_up'] = {'adv_effects': {'sequence': [{'gain_': {'type': 'vp', 'amount': 1}}]}}

In [ ]:
with open('dragon_cards_test.json', 'w') as f:
    json.dump(dragon_dict, f, indent=4)

Convert cave cards

In [7]:
# save the dragon cards first in json format
cave_cards = cards_df[cards_df['type'] == 'Cave']
cave_cards = cave_cards[['number','ability']]
# rename ability to text
cave_cards = cave_cards.rename(columns={'ability':'text'})

cave_cards.info()
cave_cards

<class 'pandas.core.frame.DataFrame'>
Index: 75 entries, 183 to 257
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   number  75 non-null     int64
 1   text    75 non-null     object
dtypes: int64(1), object(1)
memory usage: 1.8+ KB

     number                                               text
183       1  Activate the [OncePerRound-v2] ability on any ...
184       2  Activate the [WhenPlayed] ability on any drago...
185       3  Cache [AnyResource][AnyResource] from the gene...
186       4  Cache [AnyResource][AnyResource] from the gene...
187       5                     Gain [AnyResource]. Lay [Egg].
..      ...                                                ...
253      71  Up to 3x, pay [CaveCard] to gain [DragonGuild]...
254      72  Up to 3x, pay [DragonCard] to gain [DragonGuil...
255      73  Up to 3x, pay [DragonCard] to lay [Egg][Egg]. ...
256      74  Up to 3x, pay [Egg] to gain [AnyResource][AnyR...
257      75  Up to 3x, pay [Egg] to gain [DragonGuild]. Eac...

[75 rows x 2 columns]

In [19]:
cave_dict = cave_cards.to_dict(orient='records')
# we will reformat the ability key to be a list of dicts
# each dict will describe one ability
for card in cave_dict:
    ability_string = card['text']
    ability_info = {'adv_effects': {}}
    # split text by commas and periods
    as1 = ability_string.split(',')
    ability_strings = []
    for a in as1:
        ability_strings.extend(a.split('.'))
    # process each string
    for a in ability_strings:
        a = a.lower()
        if 'up to' in a:
            ability_info['max_uses'] = int(a[-2])
        if 'pay' in a:
            ability_info['cost'] = {}
            ability_info['cost'][a] = 1
        if 'may' in a:
            ability_info['adv_effects']['choice'] = []
        if 'gain' in a or 'lay [egg]' in a:
            gain_list = ability_info['adv_effects'].get('sequence', [])
            gain_list.append({'gain_': {'type': a, 'amount': 1}})
            ability_info['adv_effects']['sequence'] = gain_list
        if 'opponent' in a:
            ability_info['opponent_effect'] = {'adv_effects': {}}
    # update the card
    card['when_played'] = ability_info

In [ ]:
with open('cave_cards_test.json', 'w') as f:
    json.dump(cave_dict, f, indent=4)